# Utilizar una imagen base oficial de Python
FROM python:3.11-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de requisitos primero para aprovechar la caché de capas de Docker
COPY interfaz/requirements_app.txt .

# Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements_app.txt

# Copiar el resto de los archivos necesarios para la aplicación desde el directorio 'interfaz'
COPY interfaz/ .

# Exponer el puerto en el que se ejecutará la aplicación Dash
EXPOSE 8050

# Definir el comando para ejecutar la aplicación
CMD ["python", "app.py"]