# Usar una imagen base oficial de Python
FROM python:3.11

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de requisitos y el script de la aplicación al directorio de trabajo
COPY requirements_app.txt /app/
COPY app.py /app/

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements_app.txt

# Exponer el puerto que utiliza Dash
EXPOSE 8050

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]