# Usar una imagen base oficial de Python para AWS Lambda
FROM public.ecr.aws/lambda/python:3.12

# Copiar el archivo del script Python y cualquier otro archivo necesario al contenedor
COPY scrapping_s3_meff.py ./
COPY requirements_2.txt .

# Instalar las dependencias Python
RUN pip install --no-cache-dir -r requirements_2.txt

# Establecer el comando para ejecutar tu aplicación
CMD ["scrapping_s3_meff.lambda_handler"]