name: Actualización App

on:
  push:
    branches:
      - main
    paths:
      - 'interfaz/app.py'

env:
  AWS_REGION: eu-west-3

defaults:
  run:
    shell: bash

jobs:
  build_and_push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login_ecr

      - name: Build and push Docker image
        run: |
          ECR_REGISTRY=${{ steps.login_ecr.outputs.registry }}
          IMAGE_TAG=${{ github.sha }}
          ECR_REPOSITORY=app_volatility_ecr
          DOCKERFILE_PATH=interfaz/Dockerfile
          cd interfaz
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_PATH .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
