name: Run Python Tests and flake 8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Instala flake8 para verificar el estilo del código
          pip install -r requirements.txt  # Si tienes un archivo de requisitos para tus pruebas unitarias, agrégalo aquí
      - name: Run flake8
        run: flake8 . 
      - name: Run tests with pytest
        run: pytest 