name: Run Python Tests and flake 8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Asegúrate de que esta versión sea la que soporte Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Asegúrate de que esta versión sea la que soporte Node.js 20
      with:
        python-version: '3.11'  # Asegúrate de usar la versión de Python que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Detener el workflow si hay errores de estilo
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Salida de advertencia para otros errores de estilo
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

