name: Run Python Tests and Flake8

on:
  push:
    paths:
      - 'tests/test_interfaz_final.py'
  pull_request:
    paths:
      - 'tests/test_interfaz_final.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

    - name: Lint with flake8 on Specific File
      run: |
        # Ejecutar flake8 solo para el archivo específico
        flake8 tests/test_interfaz_final.py --count --show-source --statistics --exit-zero --max-complexity=10 --max-line-length=127

    - name: Test with pytest on Specific File
      run: |
        # Ejecutar pytest solo para el archivo específico
        pytest tests/test_interfaz_final.py

